
version: '3.8'

services:
  code-runner:
    build: .
    ports:
      - "3000:3000"
    container_name: code-runner
    stdin_open: true
    tty: true
    mem_limit: 512m
    cpus: "0.5"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /usr/src/app/temp:exec
